version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: bun run --cwd apps/backend start
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - API_KEY=${API_KEY}
    ports:
      - '5000:5000'

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bun run --cwd apps/web start
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    ports:
      - '3000:3000'
