name: Build and Deploy Web & Backend

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for orphan branch pushes

      - name: Set Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build App
        run: |
          bun run build
        working-directory: ${{ github.workspace }}

      - name: Save Web Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: apps/web/dist

      - name: Save Backend Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-dist
          path: apps/backend/dist

      - name: Make a stupid empty branch and do nothing except for make sure everything else is not poluted
        run: |
          git checkout --orphan stupid-branch
          git rm -rf . > /dev/null 2>&1 || true

          git add --all
          git commit -m "stupid-branch init"

      - name: Download Backend Artifacts
        uses: actions/download-artifact@v4
        with:
          name: backend-dist
          path: backend-dist

      - name: Deploy Backend Artifacts to backend branch
        run: |
          git checkout --orphan backend
          git rm -rf . > /dev/null 2>&1 || true

          cp -r backend-dist/* .
          rm -rf backend-dist

          git add --all
          git commit -m "Deploy Backend"
          git push -f origin backend

      - name: Download Web Artifacts
        uses: actions/download-artifact@v4
        with:
          name: web-dist
          path: web-dist

      - name: Deploy Web Artifacts to web branch
        run: |
          git checkout --orphan web
          git rm -rf . > /dev/null 2>&1 || true

          cp -r web-dist/* .
          rm -rf web-dist

          touch .nojekyll

          git add --all
          git commit -m "Deploy Web"
          git push -f origin web

