name: Build and Deploy Web & Backend

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to push to other branches

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build Web App
        run: |
          cd apps/web
          bun run build
        env:
          NODE_ENV: production

      - name: Deploy Web Artifacts to web branch
        run: |
          # Paths
          BUILD_DIR=apps/web/dist
          TEMP_DEPLOY_DIR=web-deploy

          # Make sure build was successful
          if [ ! -d "$BUILD_DIR" ]; then
            echo "Web build directory not found at $BUILD_DIR"
            exit 1
          fi

          # Copy build artifacts to a temp folder outside git context
          mkdir $TEMP_DEPLOY_DIR
          cp -r $BUILD_DIR/* $TEMP_DEPLOY_DIR/

          # Clean working directory and switch orphan branch
          git checkout --orphan web
          git rm -rf . > /dev/null 2>&1 || true

          # Move build files into place
          cp -r $TEMP_DEPLOY_DIR/* .
          rm -rf $TEMP_DEPLOY_DIR

          touch .nojekyll  # Optional for GitHub Pages

          git add --all
          git commit -m "Deploy Web"
          git push -f origin web

      - name: Build Backend
        run: |
          cd apps/backend
          bun run build

      - name: Deploy Backend Artifacts to backend branch
        run: |
          BUILD_DIR=apps/backend/dist
          TEMP_DEPLOY_DIR=backend-deploy

          if [ ! -d "$BUILD_DIR" ]; then
            echo "Backend build directory not found at $BUILD_DIR"
            exit 1
          fi

          mkdir $TEMP_DEPLOY_DIR
          cp -r $BUILD_DIR/* $TEMP_DEPLOY_DIR/

          git checkout --orphan backend
          git rm -rf . > /dev/null 2>&1 || true

          cp -r $TEMP_DEPLOY_DIR/* .
          rm -rf $TEMP_DEPLOY_DIR

          git add --all
          git commit -m "Deploy Backend"
          git push -f origin backend
