name: Build and Deploy Web & Backend

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to push to other branches

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build Web App
        run: |
          cd apps/web
          bun run build
        env:
          NODE_ENV: production

      - name: Deploy Web Artifacts to web branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          BUILD_DIR=apps/web/dist

          # Make sure build folder exists
          if [ ! -d "$BUILD_DIR" ]; then
            echo "Build directory not found!"
            exit 1
          fi

          # Save the current directory as a safe working space
          mkdir tmp-deploy
          cp -r $BUILD_DIR/* tmp-deploy/

          # Switch to orphan branch and clean it
          git switch --orphan web
          git rm -rf .

          # Copy build files into root
          cp -r tmp-deploy/* .
          rm -rf tmp-deploy

          touch .nojekyll  # Optional for GitHub Pages

          git add .
          git commit -m "Deploy Web"
          git push -f origin web

      - name: Build Backend
        run: |
          cd apps/backend
          bun run build

      - name: Deploy Backend Artifacts to backend branch
        run: |
          git switch --orphan backend
          git rm -rf .

          cp -r apps/backend/dist/* .

          git add .
          git commit -m "Deploy Backend"
          git push -f origin backend
