name: Build and Deploy Web & Backend

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for orphan branch pushes

      - name: Set Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build Web App
        run: |
          cd apps/web
          bun run build
        working-directory: ${{ github.workspace }}

      - name: Save Web Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: apps/web/dist

      - name: Build Backend App
        run: |
          cd apps/backend
          bun run build
        working-directory: ${{ github.workspace }}

      - name: Save Backend Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-dist
          path: apps/backend/dist

      - name: Download Web Artifacts
        uses: actions/download-artifact@v4
        with:
          name: web-dist
          path: web-dist-copy

      - name: Deploy Web Artifacts to web branch
        run: |
          git checkout --orphan web
          git rm -rf . > /dev/null 2>&1 || true

          cp -r web-dist-copy/* .
          rm -rf web-dist-copy

          touch .nojekyll

          git add --all
          git commit -m "Deploy Web"
          git push -f origin web

      - name: Download Backend Artifacts
        uses: actions/download-artifact@v4
        with:
          name: backend-dist
          path: backend-dist-copy

      - name: Deploy Backend Artifacts to backend branch
        run: |
          git checkout --orphan backend
          git rm -rf . > /dev/null 2>&1 || true

          cp -r backend-dist-copy/* .
          rm -rf backend-dist-copy

          git add --all
          git commit -m "Deploy Backend"
          git push -f origin backend

      - name: Clean all folders in web branch before deploy
        run: |
          git checkout web
          git rm -rf . > /dev/null 2>&1 || true
          git clean -fdx -f

          cp -r web-dist-copy/* .
          rm -rf web-dist-copy

          touch .nojekyll
          git add --all
          git commit -m "Deploy Web clean"
          git push -f origin web
